Remove redundant temperature sensor ID for CPU cores
YADRO-KNS/vesnin-xml pull request #2
Opened 2018-12-18 11:03 UTC by artemsen

Removed sensors:
CORE12, IPMI_SENSOR_ID 0xA9
CORE24, IPMI_SENSOR_ID 0xAE
CORE36, IPMI_SENSOR_ID 0xAF

Signed-off-by: Artem Senichev <a.senichev@yadro.com>

2018-12-25 12:15 UTC, AlexanderAmelkin requested changes
Please explain in the commit log _why_ or _what for_ those sensors are removed.

2018-12-25 12:18 UTC, artemsen commented
It's just a mistyping. All other sensors of CPU cores have been already removed by MSI.

2018-12-25 12:28 UTC, AlexanderAmelkin commented
Good. But that must be stated in the commit log so that later we don't have to wonder why you did what you did.

2018-12-26 14:09 UTC, AlexanderAmelkin approved these changes

2018-12-26 14:09 UTC, merged